export const postList = [
  {
    author: "author",
    content: "content",
    detail_url: "detail_url",
    get_comment_count: "4",
    get_like_count: "3",
    get_view_count: "5",
    image: "",
    published_date: "published_date",
    slug: "slug",
    status: "status",
    title: "title",
    hasUserLiked: false,
  },
  {
    author: "author",
    content: "content",
    detail_url: "detail_url",
    get_comment_count: "8",
    get_like_count: "3",
    get_view_count: "5",
    image: "",
    published_date: "published_date",
    slug: "slug",
    status: "status",
    title: "title",
    hasUserLiked: false,
  },
  {
    author: "author",
    content: "content",
    detail_url: "detail_url",
    get_comment_count: "9",
    get_like_count: "3",
    get_view_count: "5",
    image: "",
    published_date: "published_date",
    slug: "slug",
    status: "status",
    title: "title",
    hasUserLiked: false,
  },
  {
    author: "author",
    content: "content",
    detail_url: "detail_url",
    get_comment_count: "2",
    get_like_count: "3",
    get_view_count: "5",
    image: "",
    published_date: "published_date",
    slug: "slug",
    status: "status",
    title: "title",
    hasUserLiked: false,
  },
];
